# Generated by Django 4.2 on 2023-04-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_alter_course_unique_together_lession'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lession',
            table=None,
        ),
    ]
