# Generated by Django 4.2 on 2023-04-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='tag',
            new_name='tags',
        ),
    ]
